name: media_dl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  macos:
    generate: true
  windows:
    generate: true
  linux:
    generate: true
  web:
    generate: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#7B1FA2"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter_native_splash:
  color: "#7B1FA2"
  color_dark: "#4A148C"
  image: "assets/app_icon_512.png"
  image_dark: "assets/app_icon_512.png"
  android: true
  web: true
  android_12:
    color: "#7B1FA2"
    color_dark: "#4A148C"
    image: "assets/app_icon_512.png"
    image_dark: "assets/app_icon_512.png"
